@startuml
!theme spacelab

package "Auth & User" {
  class User {
    id
    name
    email
    role
  }

  class RefreshToken
  class Follower
  class Review
}

package "Roles" {
  class Teacher
  class Student
  class Center
}

package "Academic" {
  class Course
  class Lesson
  class Exam
  class Homework
  class Note
  class BookedLesson
}

package "Scheduling" {
  class WeeklySchedule
  class TeacherDay
  class BookedWeekly
}

package "Social" {
  class Post
  class Comment
  class Like
}

package "Chat" {
  class Conversation
  class Message
  class UserConversation
}

package "Notification" {
  class Notification
}

' ===== العلاقات =====

User --> Teacher
User --> Student
User --> Center

User --> RefreshToken
User --> Follower
User --> Review

Teacher --> Course
Teacher --> Lesson

Course --> Lesson
Course --> Exam
Course --> Homework
Course --> Note

Student --> BookedLesson
Lesson --> BookedLesson

Center --> WeeklySchedule
WeeklySchedule --> TeacherDay
Teacher --> TeacherDay

Student --> BookedWeekly
TeacherDay --> BookedWeekly

User --> Post
Post --> Comment
Post --> Like
User --> Comment
User --> Like

Conversation --> Message
User --> Message
User --> UserConversation
Conversation --> UserConversation

User --> Notification

@enduml