-- AlterTable
ALTER TABLE "Center" ALTER COLUMN "star" SET DEFAULT 0,
ALTER COLUMN "star" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Teacher" ALTER COLUMN "star" SET DEFAULT 0,
ALTER COLUMN "star" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "TeacherByCenter" ALTER COLUMN "star" SET DEFAULT 0,
ALTER COLUMN "star" SET DATA TYPE DOUBLE PRECISION;
