const centerData = {
  id: '1',
  name: 'سنتر المتخصص التعليمي',
  slug: 'specialist-center',
  // coverImage: centerCover,
  logo: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?q=80&w=2070',
  location: 'القاهرة - ألف مسكن',
  bio: 'مركز تعليمي متخصص يضم نخبة من أفضل المعلمين بكافة التخصصات لتقديم محتوى تعليمي متميز لجميع المراحل.',
  subjects: ['اللغة العربية', 'الرياضيات', 'الفيزياء', 'الكيمياء', 'الأحياء'],
  stages: ['المرحلة الإعدادية', 'المرحلة الثانوية'],
  systems: ['عربي', 'لغات'],
  contact: {
    phones: '01234567890',
    whats: '01098765432',
    email: 'info@specialist.com',
  },
  posts: [
    {
      id: 1,
      author: 'سنتر المتخصص التعليمي',
      time: 'منذ ساعتين',
      content:
        'تنبيه هام لطلاب الصف الثاني الثانوي... تم تعديل موعد حصة اللغة العربية لتكون يوم السبت.',
      image: null,
    },
    {
      id: 2,
      author: 'سنتر المتخصص التعليمي',
      time: 'أمس',
      content: 'مراجعة ليلة الامتحان في الفيزياء مع د. محمود حسن.',
      image:
        'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?q=80&w=2070',
    },
    {
      id: 3,
      author: 'سنتر المتخصص التعليمي',
      time: 'أمس',
      content: 'مراجعة ليلة الامتحان في الفيزياء مع د. محمود حسن.',
      image:
        'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?q=80&w=2070',
    },
    {
      id: 4,
      author: 'سنتر المتخصص التعليمي',
      time: 'أمس',
      content: 'مراجعة ليلة الامتحان في الفيزياء مع د. محمود حسن.',
      image:
        'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?q=80&w=2070',
    },
  ],
};
const teachersData = [
  {
    id: 1,
    name: 'أ. حسن علي',
    subject: 'اللغة العربية',
    stage: 'المرحلة الابتدائية',
    grade: 'الصف الثالث الابتدائي',
    experience: '25 سنة',
    yearsInCenter: 'خبرة 8 أعوام',
    image: 'teacher1',
    bio: 'خبير ومدرس أول لغة عربية، خبرة أكثر من 25 عام في تدريس المرحلة الابتدائية...',
    socials: { facebook: '#', instagram: '#', twitter: '#' },
  },
  {
    id: 2,
    name: 'أ. منال علي',
    subject: 'اللغة العربية',
    stage: 'المرحلة الثانوية',
    grade: 'الصف الثالث الثانوي',
    experience: '25 سنة',
    yearsInCenter: 'خبرة 8 أعوام',
    image: 'image 1',
    bio: 'خبير ومدرس أول لغة عربية، خبرة أكثر من 25 عام في تدريس المرحلة الابتدائية...',
    socials: { facebook: '#', instagram: '#', twitter: '#' },
  },
  {
    id: 3,
    name: 'أ. محمود لطفي',
    subject: 'اللغة الإنجليزية  ',
    stage: 'المرحلة الإعدادية',
    grade: 'الصف الثاني الإعدادية',
    experience: '25 سنة',
    yearsInCenter: 'خبرة 8 أعوام',
    image: 'image 2',
    bio: 'خبير ومدرس أول لغة عربية، خبرة أكثر من 25 عام في تدريس المرحلة الابتدائية...',
    socials: { facebook: '#', instagram: '#', twitter: '#' },
  },
  {
    id: 4,
    name: 'أ. حسن علي',
    subject: 'اللغة العربية',
    stage: 'المرحلة الابتدائية',
    grade: 'الصف الثالث الابتدائي',
    experience: '25 سنة',
    yearsInCenter: 'خبرة 8 أعوام',
    image: 'image 3',
    bio: 'خبير ومدرس أول لغة عربية، خبرة أكثر من 25 عام في تدريس المرحلة الابتدائية...',
    socials: { facebook: '#', instagram: '#', twitter: '#' },
  },
  {
    id: 5,
    name: 'أ. حسن علي',
    subject: 'اللغة العربية',
    stage: 'المرحلة الابتدائية',
    grade: 'الصف الثالث الابتدائي',
    experience: '25 سنة',
    yearsInCenter: 'خبرة 8 أعوام',
    image: 'image 4',
    bio: 'خبير ومدرس أول لغة عربية، خبرة أكثر من 25 عام في تدريس المرحلة الابتدائية...',
    socials: { facebook: '#', instagram: '#', twitter: '#' },
  },
  {
    id: 6,
    name: 'أ. حسن علي',
    subject: 'اللغة العربية',
    stage: 'المرحلة الابتدائية',
    grade: 'الصف الثالث الابتدائي',
    experience: '25 سنة',
    yearsInCenter: 'خبرة 8 أعوام',
    image: 'image 5',
    bio: 'خبير ومدرس أول لغة عربية، خبرة أكثر من 25 عام في تدريس المرحلة الابتدائية...',
    socials: { facebook: '#', instagram: '#', twitter: '#' },
  },
  {
    id: 7,
    name: 'أ. حسن علي',
    subject: 'اللغة العربية',
    stage: 'المرحلة الابتدائية',
    grade: 'الصف الثالث الابتدائي',
    experience: '25 سنة',
    yearsInCenter: 'خبرة 8 أعوام',
    image: 'image 6',
    bio: 'خبير ومدرس أول لغة عربية، خبرة أكثر من 25 عام في تدريس المرحلة الابتدائية...',
    socials: { facebook: '#', instagram: '#', twitter: '#' },
  },
  {
    id: 8,
    name: 'أ. حسن علي',
    subject: 'اللغة العربية',
    stage: 'المرحلة الابتدائية',
    grade: 'الصف الثالث الابتدائي',
    experience: '25 سنة',
    yearsInCenter: 'خبرة 8 أعوام',
    image: 'image 7',
    bio: 'خبير ومدرس أول لغة عربية، خبرة أكثر من 25 عام في تدريس المرحلة الابتدائية...',
    socials: { facebook: '#', instagram: '#', twitter: '#' },
  },
  {
    id: 9,
    name: 'أ. حسن علي',
    subject: 'اللغة العربية',
    stage: 'المرحلة الابتدائية',
    grade: 'الصف الثالث الابتدائي',
    experience: '25 سنة',
    yearsInCenter: 'خبرة 8 أعوام',
    image: 'image 8',
    bio: 'خبير ومدرس أول لغة عربية، خبرة أكثر من 25 عام في تدريس المرحلة الابتدائية...',
    socials: { facebook: '#', instagram: '#', twitter: '#' },
  },
];

const scheduleData = [
  {
    day: 'السبت',
    lessons: [
      {
        id: 1,
        teacher: 'أ. علي الهواري',
        subject: 'الفيزياء',
        grade: 'الصف الثالث الثانوي',
        time: '12:00 م',
        status: 'available',
      },
    ],
  },
  {
    day: 'الأحد',
    lessons: [
      {
        id: 2,
        teacher: 'أ. عبدالله الشيخ',
        subject: 'الرياضيات التطبيقية',
        grade: 'الصف الثالث الثانوي',
        time: '9:00 ص',
        status: 'booked',
      },
      {
        id: 3,
        teacher: 'أ. عبدالله الشيخ',
        subject: 'الإحصاء',
        grade: 'الصف الثالث الثانوي',
        time: '11:00 ص',
        status: 'booked',
      },
    ],
  },
  {
    day: 'الإثنين',
    lessons: [
      {
        id: 4,
        teacher: 'أ. عبدالله الشيخ',
        subject: 'الرياضيات التطبيقية',
        grade: 'الصف الثاني الثانوي',
        time: '9:00 ص',
        status: 'booked',
      },
      {
        id: 5,
        teacher: 'أ. عبدالله الشيخ',
        subject: 'الإحصاء',
        grade: 'الصف الأول الثانوي',
        time: '11:00 ص',
        status: 'booked',
      },
    ],
  },
  // أضف باقي الأيام...
];

const allAssignments = [
  {
    id: 1,
    title: 'الواجب المنزلى:',
    subject: 'فيزياء',
    deadline: '25 أكتوبر - 10:00م',
  },
  {
    id: 2,
    title: 'الواجب المنزلى:',
    subject: 'كيمياء',
    deadline: '26 أكتوبر - 09:00م',
  },
  {
    id: 3,
    title: 'الواجب المنزلى:',
    subject: 'رياضيات',
    deadline: '27 أكتوبر - 08:00م',
  },
  {
    id: 4,
    title: 'الواجب المنزلى:',
    subject: 'أحياء',
    deadline: '28 أكتوبر - 07:00م',
  },
];
const allExams = [
  {
    id: 1,
    title: 'امتحان نصف الترم:',
    subject: 'فيزياء',
    date: '20 أكتوبر - 9:00',
    duration: '60 دقيقة',
  },
  {
    id: 2,
    title: 'امتحان شهرى:',
    subject: 'كيمياء',
    date: '21 أكتوبر - 10:00',
    duration: '45 دقيقة',
  },
  {
    id: 3,
    title: 'امتحان تجريبى:',
    subject: 'لغة عربية',
    date: '22 أكتوبر - 11:00',
    duration: '90 دقيقة',
  },
];
const lessonsData = {
  '5': [
    {
      id: 1,
      subject: 'الرياضيات - أ/ خالد',
      center: 'سنتر النور - الدقى',
      time: 'الساعة 4:00 عصراً',
    },
    {
      id: 2,
      subject: 'الفيزياء - أ/ محمود',
      center: 'أونلاين',
      time: 'الساعة 8:00 مساءً',
    },
  ],
};

const postsData = [
  {
    id: 1,
    author: 'أ. حسن علي عبدالله',
    role: 'رياضيات - المرحلة الثانوية',
    time: '2 ي . الساعة 8:00 م',
    content: 'غداً الثلاثاء محاضرة الجبر',
    comments: 20,
    likes: 18,
  },
  {
    id: 2,
    author: 'أ. حسن علي عبدالله',
    role: 'رياضيات - المرحلة الثانوية',
    time: '2 ي . الساعة 8:00 م',
    content:
      'بكره الثلاثاء 30/9 \nجاهز تفهم الرياضيات........... بكل بساطه............ يلا بينا \nمواعيد محاضراتنا إن شاء الله',
    comments: 2,
    likes: 6,
  },
];

const students = [
  {
    id: 1,
    name: 'أحمد محمود علي',
    grade: 'الثالث الثانوي',
    course: 'دورة الجبر الشاملة',
    date: '2024-12-01',
    time: '10:30 ص',
  },
  {
    id: 2,
    name: 'سارة كمال حسن',
    grade: 'الثالث الثانوي',
    course: 'دورة التفاضل',
    date: '2024-12-01',
    time: '11:15 ص',
  },
  {
    id: 3,
    name: 'ياسين مصطفى',
    grade: 'الثاني الثانوي',
    course: 'دورة الهندسة الفراغية',
    date: '2024-11-30',
    time: '09:45 ص',
  },
  {
    id: 4,
    name: 'ليلى عبد العزيز',
    grade: 'الثالث الثانوي',
    course: 'دورة الاحصاء والاحتمالات',
    date: '2024-11-28',
    time: '01:20 م',
  },
  {
    id: 5,
    name: 'ليلى عبد العزيز',
    grade: 'الثالث الثانوي',
    course: 'دورة الاحصاء والاحتمالات',
    date: '2024-11-28',
    time: '01:20 م',
  },
  {
    id: 6,
    name: 'ليلى عبد العزيز',
    grade: 'الثالث الثانوي',
    course: 'دورة الاحصاء والاحتمالات',
    date: '2024-11-28',
    time: '01:20 م',
  },
  {
    id: 7,
    name: 'ليلى عبد العزيز',
    grade: 'الثالث الثانوي',
    course: 'دورة الاحصاء والاحتمالات',
    date: '2024-11-28',
    time: '01:20 م',
  },
  {
    id: 8,
    name: 'ليلى عبد العزيز',
    grade: 'الثالث الثانوي',
    course: 'دورة الاحصاء والاحتمالات',
    date: '2024-11-28',
    time: '01:20 م',
  },
  {
    id: 9,
    name: 'ليلى عبد العزيز',
    grade: 'الثالث الثانوي',
    course: 'دورة الاحصاء والاحتمالات',
    date: '2024-11-28',
    time: '01:20 م',
  },
];

const coursesData = [
  {
    id: 1,
    title: 'دورة الجبر الشاملة',
    grade: 'الأول الثانوي',
    students: 118,
    price: 1200,
    rating: 4.8,
    reviews: 35,
  },
  {
    id: 2,
    title: 'دورة التفاضل والتكامل',
    grade: 'الثاني الثانوي',
    students: 142,
    price: 1400,
    rating: 4.9,
    reviews: 56,
  },
  {
    id: 3,
    title: 'دورة الجبر الشاملة',
    grade: 'الثالث الثانوي',
    students: 118,
    price: 1200,
    rating: 4.8,
    reviews: 35,
  },
  {
    id: 4,
    title: 'دورة التفاضل والتكامل',
    grade: 'الأول الثانوي',
    students: 142,
    price: 1400,
    rating: 4.9,
    reviews: 56,
  },
  {
    id: 5,
    title: 'دورة الجبر الشاملة',
    grade: 'الثاني الثانوي',
    students: 118,
    price: 1200,
    rating: 4.8,
    reviews: 35,
  },
  {
    id: 6,
    title: 'دورة التفاضل والتكامل',
    grade: 'الثالث الثانوي',
    students: 142,
    price: 1400,
    rating: 4.9,
    reviews: 56,
  },
  {
    id: 7,
    title: 'دورة الجبر الشاملة',
    grade: 'الأول الثانوي',
    students: 118,
    price: 1200,
    rating: 4.8,
    reviews: 35,
  },
  {
    id: 8,
    title: 'دورة التفاضل والتكامل',
    grade: 'الثاني الثانوي',
    students: 142,
    price: 1400,
    rating: 4.9,
    reviews: 56,
  },
  {
    id: 9,
    title: 'دورة الجبر الشاملة',
    grade: 'الثالث الثانوي',
    students: 118,
    price: 1200,
    rating: 4.8,
    reviews: 35,
  },
  {
    id: 10,
    title: 'دورة التفاضل والتكامل',
    grade: 'الأول الثانوي',
    students: 142,
    price: 1400,
    rating: 4.9,
    reviews: 56,
  },
  {
    id: 11,
    title: 'دورة الجبر الشاملة',
    grade: 'الثالث الثانوي',
    students: 118,
    price: 1200,
    rating: 4.8,
    reviews: 35,
  },
  {
    id: 12,
    title: 'دورة التفاضل والتكامل',
    grade: 'الثالث الثانوي',
    students: 142,
    price: 1400,
    rating: 4.9,
    reviews: 56,
  },
  {
    id: 13,
    title: 'دورة الجبر الشاملة',
    grade: 'الأول الثانوي',
    students: 118,
    price: 1200,
    rating: 4.8,
    reviews: 35,
  },
  {
    id: 14,
    title: 'دورة التفاضل والتكامل',
    grade: 'الثاني الثانوي',
    students: 142,
    price: 1400,
    rating: 4.9,
    reviews: 56,
  },
];

const lessons = [
  {
    id: 1,
    title: 'الأعداد المركبة',
    duration: '45 دقيقة',
    date: '01 - 03 - 2025',
    isLocked: false,
  },
  {
    id: 2,
    title: 'الأعداد المركبة - خواص الوحدة التخيلية',
    duration: '45 دقيقة',
    date: '01 - 03 - 2025',
    isLocked: false,
  },
  {
    id: 3,
    title: 'تطبيقات علي خواص الوحدة التخيلية',
    duration: '45 دقيقة',
    date: '01 - 03 - 2025',
    isLocked: true,
  },
];

const notes = [
  {
    id: 1,
    title: 'الأعداد المركبة',
    info: '32 MB . 45 صفحة',
    date: '02 - 03 - 2026',
    isLocked: false,
  },
  {
    id: 2,
    title: 'الأعداد المركبة - خواص الوحدة التخيلية',
    info: '12 MB . 21 صفحة',
    date: '09 - 03 - 2026',
    isLocked: false,
  },
  {
    id: 3,
    title: 'الصورة الجبرية للعدد المركب',
    info: 'احجز الحصة لفتح المذكرة',
    date: '16 - 03 - 2026',
    isLocked: true,
  },
];
const homework = [
  {
    id: 1,
    title: 'واجب علي الأعداد المركبة',
    info: '32 MB . 22 صفحة',
    date: '12 - 04 - 2026',
    isLocked: false,
  },
  {
    id: 2,
    title: 'الأعداد المركبة - خواص الوحدة التخيلية',
    info: '12 MB . 21 صفحة',
    date: '09 - 03 - 2026',
    isLocked: false,
  },
  {
    id: 3,
    title: 'الصورة الجبرية للعدد المركب',
    info: 'احجز الحصة لفتح المذكرة',
    date: '16 - 03 - 2026',
    isLocked: true,
  },
];
const exam = [
  {
    id: 1,
    title: 'امتحان علي الأعداد المركبة',
    info: '32 MB . 45 صفحة',
    date: '22 - 02 - 2026',
    isLocked: false,
  },
  {
    id: 2,
    title: 'الأعداد المركبة - خواص الوحدة التخيلية',
    info: '12 MB . 21 صفحة',
    date: '09 - 03 - 2026',
    isLocked: true,
  },
  {
    id: 3,
    title: 'الصورة الجبرية للعدد المركب',
    info: 'احجز الحصة لفتح المذكرة',
    date: '16 - 03 - 2026',
    isLocked: true,
  },
];
